"use client";
import {useEffect,useMemo,useState} from "react";
import {architect,patterns} from "../lib/architect.mjs";

const fallback={company:"Select an opportunity",score:0,industry:"",ownership:"",trigger:"",exposure:"",tension:"",hypothesis:"",unknown:"",question:"",contact:"",status:"Research"};
const gbp=n=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(Number(n)||0);
const nav=[{group:"INTELLIGENCE",items:[["opportunities","Opportunities","◎"],["outside","Outside-In","◇"]]},{group:"CAPABILITY",items:[["strawman","Strawman","▱"],["talent","Talent Network","◌"],["engagements","Engagements","◫"],["patterns","Patterns Library","⌁"],["learning","Learning Engine","↗"]]},{group:"SYSTEM",items:[["settings","Settings","⚙"],["integrations","Integrations","↔"]]}];
const titles={opportunities:["Opportunity Engine","Opportunities"],outside:["INTELLIGENCE","Outside-In + Capability Architect"],strawman:["CAPABILITY","Editable Strawman"],talent:["CAPABILITY","Talent Network"],engagements:["CAPABILITY","Engagements"],patterns:["CAPABILITY","Patterns Library"],learning:["CAPABILITY","Learning Engine"],settings:["SYSTEM","Settings"],integrations:["SYSTEM","Integrations"]};

export default function Home(){
 const[tab,setTab]=useState("opportunities"),[opps,setOpps]=useState([]),[selected,setSelected]=useState(fallback),[draft,setDraft]=useState(fallback),[query,setQuery]=useState(""),[status,setStatus]=useState("All"),[sync,setSync]=useState({loading:true,error:"",at:""}),[approval,setApproval]=useState("Draft"),[buy,setBuy]=useState(480),[sell,setSell]=useState(650),[days,setDays]=useState(60),[saved,setSaved]=useState([]),[clientView,setClientView]=useState(false);
 const load=async()=>{setSync(s=>({...s,loading:true,error:""}));try{const res=await fetch('/api/opportunities',{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not read Prospect Engine');setOpps(data.opportunities||[]);if(selected.company===fallback.company&&data.opportunities?.[0]){setSelected(data.opportunities[0]);setDraft(data.opportunities[0])}setSync({loading:false,error:"",at:data.syncedAt})}catch(e){setSync({loading:false,error:e.message,at:""})}};
 useEffect(()=>{load()},[]);
 const capability=useMemo(()=>architect(draft),[draft]);
 const statuses=useMemo(()=>["All",...Array.from(new Set(opps.map(o=>o.status||"Research"))).slice(0,6)],[opps]);
 const filtered=useMemo(()=>opps.filter(o=>{const hay=[o.company,o.industry,o.trigger,o.contact,o.ownership,o.buyerName,o.buyer].join(" ").toLowerCase();return(!query||hay.includes(query.toLowerCase()))&&(status==="All"||(o.status||"Research")===status)}),[opps,query,status]);
 const pick=o=>{setSelected(o);setDraft({...o});setApproval("Draft");setClientView(false);setTab("outside")};
 const investment=sell*days*Math.max(1,capability.core.length),margin=sell?Math.round((sell-buy)/sell*100):0;
 const header=titles[tab]||titles.opportunities;
 return <div className={`app ${clientView?"client-mode":""}`}><aside className="sidebar"><div className="brandCard"><div className="wordmark"><span>ELASTIC</span><span>LABS</span></div></div><div className="productName">OPPORTUNITY ENGINE</div><nav>{nav.map(section=><div className="navGroup" key={section.group}><small>{section.group}</small>{section.items.map(([key,label,icon])=><button key={key} className={tab===key?"active":""} onClick={()=>{setClientView(false);setTab(key)}}><i>{icon}</i>{label}</button>)}</div>)}</nav><div className="userCard"><div className="avatar">JA</div><div><b>Jonny Ayres</b><small>Elastic Labs</small></div><span>•••</span></div></aside><main className="workspace"><header className="topbar"><div><small>{header[0]}</small><h1>{header[1]}</h1></div><div className="topActions"><span className="liveDot">● LIVE</span>{tab==="opportunities"&&<><button onClick={load} disabled={sync.loading}>{sync.loading?"Syncing…":"↻ Sync from Google Sheet"}</button><button className="primary">+ Add opportunity</button></>}</div></header>
 {tab==="opportunities"&&<section><div className="syncLine">{sync.error?<span className="error">Sheet sync error: {sync.error}</span>:<span>Last synced {sync.at?new Date(sync.at).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"}):"when opened"} · Pipeline is the source of truth</span>}<b>{opps.length} active opportunities</b></div><div className="filters"><div className="search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search company, trigger, buyer or wedge"/></div><div className="tabs">{statuses.map(s=><button key={s} className={status===s?"on":""} onClick={()=>setStatus(s)}>{s}</button>)}</div></div><div className="tableWrap"><table><thead><tr><th>Score</th><th>Company</th><th>Why now</th><th>Status</th><th>Buyer</th><th>Next action</th><th></th></tr></thead><tbody>{filtered.map((o,i)=><tr key={`${o.company}-${i}`} onClick={()=>pick(o)}><td><span className={`score ${o.score>=90?"hot":""}`}>{o.score}</span></td><td><b>{o.company}</b><small>{o.industry}{o.ownership?` · ${o.ownership}`:""}</small></td><td><p className="truncate">{o.trigger||"Trigger requires validation"}</p></td><td><span className="status">{o.status||"Research"}</span></td><td>{o.buyerName||o.buyer||o.contact||"Validate"}</td><td><p className="truncate">{o.nextAction||"Research and qualify"}</p></td><td>→</td></tr>)}</tbody></table>{!sync.loading&&!filtered.length&&<div className="empty">No opportunities match this view.</div>}</div></section>}
 {tab==="outside"&&<section className="detailGrid"><div className="panel evidencePanel"><div className="eyebrow">OUTSIDE-IN · {draft.company}</div><div className="panelTitle"><div><h2>Evidence before prescription</h2><p>All available research below is populated from the Prospect Engine Google Sheet.</p></div><span className={`approval ${approval.toLowerCase().replaceAll(" ","-")}`}>{approval}</span></div>
 <div className="metaGrid"><div><small>SCORE / STATUS</small><p>{draft.score||0}/100 · {draft.status||""}</p></div><div><small>WEDGE</small><p>{draft.industry||""}</p></div><div><small>OWNER / BACKER</small><p>{draft.ownership||""}</p></div><div><small>SCALE</small><p>{[draft.employees&&`${draft.employees} employees`,draft.revenue&&`${draft.revenue} revenue`,draft.growth&&`${draft.growth} 12m growth`].filter(Boolean).join(" · ")}</p></div></div>
 {[['trigger','OBSERVATION · TRIGGER'],['complexity','OPERATING COMPLEXITY'],['bench','TECH / DATA BENCH'],['whyElastic','WHY ELASTIC · TENSION / HYPOTHESIS'],['unknown','KEY UNKNOWN'],['question','BEST DISCOVERY QUESTION']].map(([k,l])=><label className="field" key={k}><span>{l}</span><textarea value={draft[k]||''} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}
 <div className="metaGrid"><div><small>PRIMARY BUYER</small><p>{draft.buyer||""}</p></div><div><small>BUYER NAME</small><p>{draft.buyerName||""}</p></div><div><small>LINKEDIN / CONTACT</small><p>{draft.contactDetail||""}</p></div><div><small>LAST TOUCH</small><p>{draft.lastTouch||""}</p></div><div><small>NEXT ACTION</small><p>{draft.nextAction||""}</p></div><div><small>NEXT ACTION DATE</small><p>{draft.nextActionDate||""}</p></div><div><small>OUTSIDE-IN STATE</small><p>{draft.outsideIn||""}</p></div><div><small>LAST RESEARCHED</small><p>{draft.lastResearched||""}</p></div></div>
 <label className="field"><span>SOURCE / CONFIDENCE</span><textarea value={draft.source||''} onChange={e=>setDraft({...draft,source:e.target.value})}/></label><label className="field"><span>RESEARCH NOTES</span><textarea value={draft.notes||''} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="approvalBar"><button onClick={()=>setApproval("Ready for Review")}>Ready for review</button><button className="primary" onClick={()=>setApproval("Approved")}>Approve Outside-In</button></div></div>
 <div className="panel architectPanel"><div className="eyebrow">CAPABILITY ARCHITECT</div><h2>Smallest credible team</h2><div className="confidence"><b>{capability.core.length}-person Core</b><span>{capability.confidence}% confidence · {capability.pattern}</span></div><p className="rationale">{capability.rationale}</p><h3>CORE · REQUIRED NOW</h3>{capability.core.map((x,i)=><div className="role core" key={x.role}><span>{i+1}</span><div><b>{x.role}</b><small>{x.why}</small></div></div>)}<h3>FLEX · ACTIVATE WHEN EVIDENCE APPEARS</h3>{capability.flex.map(x=><div className="role" key={x.role}><span>+</span><div><b>{x.role}</b><small>{x.activation}</small></div></div>)}<h3>SCALE · ONLY AFTER PROOF</h3>{capability.scale.map(x=><div className="role scale" key={x.role}><span>↗</span><div><b>{x.role}</b><small>{x.condition}</small></div></div>)}<button className="wide primary" disabled={approval!=="Approved"} onClick={()=>setTab("strawman")}>{approval==="Approved"?"Build editable Strawman →":"Approve Outside-In to continue"}</button></div></section>}
 {tab==="strawman"&&<section className="proposalLayout"><div className="panel proposal"><div className="eyebrow">INITIAL DELIVERY STRAWMAN · {draft.company}</div><h2>From capability gap to a credible first mission</h2><label className="field"><span>PROPOSITION</span><textarea defaultValue={`A focused Elastic Labs capability pod to help ${draft.company} move the priority workstream forward without adding permanent capacity before the requirement is proven.`}/></label><label className="field"><span>OUTCOME</span><textarea defaultValue={draft.whyElastic||draft.tension||draft.hypothesis||"Accelerate the priority workstream while validating the long-term capability requirement."}/></label><div className="teamCards">{capability.core.map((x,i)=><article key={x.role}><small>CORE {i+1}</small><h3>{x.role}</h3><p>{x.why}</p></article>)}</div><div className="deployment"><div><small>DEPLOYMENT</small><b>12 weeks</b><p>Initial mission, then review.</p></div><div><small>CORE SHAPE</small><b>{capability.core.length} specialists</b><p>Flex remains conditional.</p></div><div><small>SELL-SIDE INVESTMENT</small><b>{gbp(investment)}</b><p>Editable commercial scenario.</p></div></div><div className="actions"><button onClick={()=>setClientView(true)}>Preview client view</button><button className="primary" onClick={()=>window.print()}>Client PDF / Print</button></div></div><div className="panel economics"><div className="eyebrow">INTERNAL ONLY</div><h2>Economics</h2><label>BUY / DAY<input type="number" value={buy} onChange={e=>setBuy(+e.target.value)}/></label><label>SELL / DAY<input type="number" value={sell} onChange={e=>setSell(+e.target.value)}/></label><label>DAYS / PERSON<input type="number" value={days} onChange={e=>setDays(+e.target.value)}/></label><div className="metric"><small>Client investment</small><b>{gbp(investment)}</b></div><div className="metric"><small>Gross margin</small><b>{margin}%</b></div><p className="guardrail">BUY rates, GP, GM, markup and bench assumptions are excluded from client view and print.</p></div></section>}
 {clientView&&<div className="clientPreview"><div className="clientHead"><div className="wordmark dark"><span>ELASTIC</span><span>LABS</span></div><button onClick={()=>setClientView(false)}>Close preview</button></div><small>CAPABILITY STRAWMAN</small><h1>{draft.company}</h1><p className="lead">A focused specialist capability pod designed around the evidence visible today, with Flex activated only when the work proves it is needed.</p><h2>The opportunity</h2><p>{draft.trigger}</p><h2>Initial Core</h2><div className="teamCards">{capability.core.map(x=><article key={x.role}><h3>{x.role}</h3><p>{x.why}</p></article>)}</div><div className="clientInvestment"><small>INDICATIVE INVESTMENT</small><b>{gbp(investment)}</b></div><button className="primary printBtn" onClick={()=>window.print()}>Print / Save PDF</button></div>}
 {tab==="talent"&&<Module title="Talent Network" copy="The specialist supply side of the engine. Match proven people to capability, not job titles." cards={[["Principal AI","AI strategy · delivery leadership","Availability to validate"],["AI Engineer","LLM · RAG · production systems","Availability to validate"],["Data Engineer","Pipelines · platforms · integration","Availability to validate"],["Product Lead","Discovery · product delivery","Availability to validate"]]}/>} {tab==="engagements"&&<Module title="Engagements" copy="Converted opportunities become delivery missions here. No fake engagement records are created." cards={[["No active engagements yet","Promote a validated opportunity after a client conversation.","Opportunity → mission → proof"]]}/>} {tab==="patterns"&&<section><div className="moduleIntro"><h2>Patterns Library</h2><p>Reusable capability patterns get stronger only when evidence moves them from hypothesis to delivery proof.</p></div><div className="cardGrid">{patterns.map(p=><article className="moduleCard" key={p.name}><span className="maturity">{p.maturity}</span><h3>{p.name}</h3>{p.core.map(x=><p key={x}>{x}</p>)}</article>)}</div></section>}{tab==="learning"&&<section><div className="moduleIntro"><h2>Learning Engine</h2><p>Hypothesised → Client-validated → Delivery-proven. The engine learns from evidence, not assumptions.</p><button className="primary" onClick={()=>setSaved([{company:draft.company,pattern:capability.pattern,maturity:"Hypothesised"},...saved])}>Capture current pattern</button></div>{saved.map((x,i)=><div className="learningRow" key={i}><b>{x.company}</b><span>{x.pattern}</span><em>{x.maturity}</em></div>)}</section>}{tab==="settings"&&<Module title="Settings" copy="Control the operating rules of the Opportunity Engine." cards={[["Approval gate","Outside-In must be approved before Strawman.","Enabled"],["Client safety","Internal economics excluded from client output.","Enabled"],["Default Core","Recommend the smallest credible team first.","2–3 people"]]}/>} {tab==="integrations"&&<Module title="Integrations" copy="Connected data sources used by this build." cards={[["Google Sheets","Elastic Labs — Prospect Engine · Pipeline","Connected live"],["Vercel","Preview and production deployment","Connected"],["HubSpot","CRM workflow","Not configured in this rebuild"]]}/>}</main></div>}
function Module({title,copy,cards}){return <section><div className="moduleIntro"><h2>{title}</h2><p>{copy}</p></div><div className="cardGrid">{cards.map(([a,b,c])=><article className="moduleCard" key={a}><h3>{a}</h3><p>{b}</p><span>{c}</span></article>)}</div></section>}
