"use client";
import { useMemo, useState } from "react";
import { architect } from "../lib/architect.mjs";
import { calculateEconomics, clientSafeCommercial } from "../lib/commercial.mjs";

const seed = [
  {company:"Lawfront",score:97,industry:"Legal",ownership:"Blixt",trigger:"PE-backed acquisition growth, refinancing, a recent CIO and an active AI rollout.",exposure:"Acquisition integration, operational data and technology delivery across a growing legal group.",tension:"Growth may create recurring integration and specialist delivery spikes that should not automatically become permanent headcount.",hypothesis:"Create a small integration capability that can prove priority workflows and flex specialist AI or infrastructure expertise only when required.",unknown:"How much central engineering, data and AI delivery capability already exists?",question:"Which integration or automation workstreams are hardest to absorb with the permanent team?",contact:"Tony McKenna · CIO"},
  {company:"AAB",score:96,industry:"Professional Services",ownership:"Goldman Sachs Alternatives",trigger:"Kreston Reeves integration, new PE ownership and an automation/integration mandate.",exposure:"Technology, data and process integration across a fast-growing accountancy platform.",tension:"A continuing buy-and-build strategy can create uneven demand for integration capability.",hypothesis:"Stand up a compact integration Core to prioritise and prove repeatable data/process integration patterns, using Flex only for specialist needs.",unknown:"Which technology, data and automation workstreams are hardest to scale internally?",question:"Where does integration demand exceed the permanent team's capacity?",contact:"Jonathon Grainger · COO"},
  {company:"JTC",score:93,industry:"Financial Services",ownership:"Public",trigger:"Interim Director of AI Transformation across 30+ jurisdictions.",exposure:"AI transformation, governance and productionisation across a complex international operating model.",tension:"Transformation leadership may be present before permanent delivery capability.",hypothesis:"Use a small AI product and engineering Core to prove one production use case before adding specialist infrastructure, data or rollout capacity.",unknown:"What permanent AI engineering and infrastructure capability sits behind the mandate?",question:"Which AI use case is closest to production but constrained by capability?",contact:"AI Transformation leadership"}
];

const gbp = n => n === null ? "Add rates" : new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(n);
const cloneTeam = r => ({core:r.core.map(x=>({...x})),flex:r.flex.map(x=>({...x})),scale:r.scale.map(x=>({...x}))});

export default function Home(){
  const [tab,setTab]=useState("opportunities");
  const [form,setForm]=useState(seed[0]);
  const [mission,setMission]=useState(seed[0].hypothesis);
  const [deployment,setDeployment]=useState("Initial 12-week mission. Core starts first; Flex activates only where discovery proves a specialist need.");
  const [team,setTeam]=useState(null);
  const [buy,setBuy]=useState("");
  const [sell,setSell]=useState("");
  const [days,setDays]=useState(60);
  const r=useMemo(()=>architect(form),[form]);
  const activeTeam=team||cloneTeam(r);
  const economics=calculateEconomics({buy,sell,days,people:activeTeam.core.length});
  const clientCommercial=clientSafeCommercial({buy,sell,days,people:activeTeam.core.length});
  const pick=o=>{setForm({...o});setMission(o.hypothesis);setTeam(null);setBuy("");setSell("");setTab("outside")};
  const build=()=>{setTeam(cloneTeam(r));setMission(form.hypothesis);setTab("strawman")};
  const updateRole=(group,index,key,value)=>setTeam(prev=>{const next=prev||cloneTeam(r);return {...next,[group]:next[group].map((x,i)=>i===index?{...x,[key]:value}:x)}});
  const removeRole=(group,index)=>setTeam(prev=>{const next=prev||cloneTeam(r);return {...next,[group]:next[group].filter((_,i)=>i!==index)}});
  const nav=[["opportunities","Trigger"],["outside","Outside-In"],["strawman","Strawman"],["proposal","Proposal"]];
  const title={opportunities:"Today’s opportunities",outside:"Outside-In",strawman:"Mission + Strawman",proposal:"Client proposal"}[tab];

  return <div className="shell">
    <aside className="no-print"><div className="brand"><i>E</i><div><b>ELASTIC LABS</b><small>Opportunity Engine</small></div></div><nav>{nav.map(x=><button key={x[0]} className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav><div className="principle"><b>Commercial loop</b><p>Trigger → Outside-In → Mission → Strawman → Proposal → Conversation.</p></div></aside>
    <main>
      <header className="no-print"><div><small>FROM SIGNAL TO SOMETHING A CLIENT CAN BUY</small><h1>{title}</h1></div><span>● Fast mode</span></header>

      {tab==="opportunities"&&<section className="no-print"><div className="intro"><b>Start with the trigger.</b><p>Pick an opportunity, sharpen the Outside-In, then turn it into the smallest credible mission.</p></div>{seed.map(o=><button key={o.company} className="opp" onClick={()=>pick(o)}><strong>{o.score}</strong><div><b>{o.company}</b><p>{o.trigger}</p><small>{o.industry} · {o.ownership} · {o.contact}</small></div><em>Build Outside-In →</em></button>)}</section>}

      {tab==="outside"&&<section className="cols no-print"><div className="panel"><small>OUTSIDE-IN · {form.company}</small><h2>What can we see?</h2>{[["trigger","TRIGGER · FACT"],["exposure","EXPOSURE · INFERENCE"],["tension","TENSION · HYPOTHESIS"],["hypothesis","MISSION HYPOTHESIS"],["unknown","CRITICAL UNKNOWN"],["question","DISCOVERY QUESTION"]].map(([k,l])=><label key={k}>{l}<textarea value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><div className="panel architect"><small>SMALLEST CREDIBLE TEAM</small><h2>{r.core.length}-person Core</h2><div className="badge">{r.confidence}% confidence · {r.pattern}</div><p>{r.rationale}</p><h3>CORE · START HERE</h3>{r.core.map((x,i)=><div key={i} className="role core"><b>{x.role}</b><small>{x.why}</small></div>)}<h3>FLEX · ONLY IF NEEDED</h3>{r.flex.map((x,i)=><div key={i} className="role"><b>{x.role}</b><small>{x.activation}</small></div>)}<h3>SCALE · AFTER PROOF</h3>{r.scale.map((x,i)=><div key={i} className="role scale"><b>{x.role}</b><small>{x.condition}</small></div>)}<button className="primary wide" onClick={build}>Turn into mission + Strawman →</button></div></section>}

      {tab==="strawman"&&<section className="no-print"><div className="panel"><small>MISSION · {form.company}</small><h2>Make it buyable</h2><label>MISSION<textarea value={mission} onChange={e=>setMission(e.target.value)}/></label><label>DEPLOYMENT<textarea value={deployment} onChange={e=>setDeployment(e.target.value)}/></label></div>
        {[["core","CORE · INITIAL TEAM","why"],["flex","FLEX · CONDITIONAL","activation"],["scale","SCALE · AFTER PROOF","condition"]].map(([group,label,reasonKey])=><div className="panel" key={group}><small>{label}</small><div className="team-edit">{activeTeam[group].map((x,i)=><article key={i} className={group}><div className="role-head"><b>{group.toUpperCase()} {i+1}</b><button onClick={()=>removeRole(group,i)}>Remove</button></div><input value={x.role} onChange={e=>updateRole(group,i,"role",e.target.value)}/><textarea value={x[reasonKey]} onChange={e=>updateRole(group,i,reasonKey,e.target.value)}/></article>)}</div></div>)}
        <div className="panel economics"><small>INTERNAL ECONOMICS · CORE ONLY</small><h2>Manual rates. No invented benchmarks.</h2><div className="econ"><label>BUY / DAY<input type="number" placeholder="Enter BUY" value={buy} onChange={e=>setBuy(e.target.value)}/></label><label>SELL / DAY<input type="number" placeholder="Enter SELL" value={sell} onChange={e=>setSell(e.target.value)}/></label><label>DAYS / PERSON<input type="number" value={days} onChange={e=>setDays(e.target.value)}/></label><div><small>Client investment</small><b>{gbp(economics.investment)}</b></div><div><small>GP / GM</small><b>{economics.complete?`${gbp(economics.grossProfit)} · ${economics.grossMargin.toFixed(1)}%`:"Add BUY + SELL"}</b></div></div><p className="muted">Flex and Scale are excluded from the initial investment until activated.</p><div className="actions"><button className="primary" onClick={()=>setTab("proposal")}>Open client proposal →</button></div></div>
      </section>}

      {tab==="proposal"&&<section className="client-proposal"><div className="proposal-top"><div><span className="mark">E</span><b>ELASTIC LABS</b></div><small>MISSION STRAWMAN · {form.company}</small></div><div className="proposal-hero"><small>PROPOSED MISSION</small><h1>{mission}</h1><p>{deployment}</p></div><div className="proposal-grid"><div><small>WHY NOW</small><h2>{form.trigger}</h2><p>{form.tension}</p></div><div><small>DISCOVERY QUESTION</small><h2>{form.question}</h2><p>We would validate this before locking the final delivery shape.</p></div></div><div className="proposal-team"><small>INITIAL CORE</small><h2>{activeTeam.core.length}-person team to start</h2><div className="team">{activeTeam.core.map((x,i)=><article key={i}><small>CORE {i+1}</small><h3>{x.role}</h3><p>{x.why}</p></article>)}</div></div><div className="proposal-conditional"><div><small>FLEX · IF EVIDENCE REQUIRES IT</small>{activeTeam.flex.map((x,i)=><p key={i}><b>{x.role}</b> · {x.activation}</p>)}</div><div><small>SCALE · AFTER PROOF</small>{activeTeam.scale.map((x,i)=><p key={i}><b>{x.role}</b> · {x.condition}</p>)}</div></div><div className="proposal-investment"><small>INITIAL CORE INVESTMENT</small><h2>{clientCommercial.complete?gbp(clientCommercial.investment):"To be confirmed"}</h2><p>{clientCommercial.complete?`${clientCommercial.people} people · ${clientCommercial.days} days per person. Flex and Scale excluded until activated.`:"Commercial rates have not yet been entered. No assumptions have been applied."}</p></div><div className="proposal-footer"><p><b>Elastic Labs</b> assembles proven specialist capability around real business missions, keeping the permanent Core small and flexing expertise only when the work requires it.</p></div><div className="actions no-print"><button onClick={()=>setTab("strawman")}>← Edit Strawman</button><button className="primary" onClick={()=>window.print()}>Download / Print PDF</button></div></section>}
    </main>
  </div>
}