const HEADERS=['Priority','Company','Score','Status','Wedge','Owner / Backer','Employees','Revenue','12m Growth','Tech / Data Bench','Complexity','Trigger','Why Elastic','Key Unknown','Best Discovery Question','Primary Buyer','Buyer Name','LinkedIn / Contact','Last Touch','Next Action','Next Action Date','Outside-In','Source / Confidence','Notes','Last Researched','Active?'];

function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++;}else if(c==='"'){quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(v=>v!==''))rows.push(row);return rows;}

// The original Sheet export contains a few human-formatted values such as 2,000+
// and 1,800+ that were not CSV-quoted. Repair those split cells before mapping so
// every research field remains aligned with its source column.
function repairRow(row){const repaired=[...row];while(repaired.length>HEADERS.length){let fixed=false;for(let i=1;i<repaired.length;i++){const left=(repaired[i-1]||'').trim(),right=(repaired[i]||'').trim();if(/^\d{1,3}$/.test(left)&&/^\d{3}(?:\+|\b)/.test(right)){repaired.splice(i-1,2,`${left},${right}`);fixed=true;break;}}if(!fixed)break;}return repaired;}

export function parsePipelineCsv(csv){const rows=parseCsv(csv);if(!rows.length)return[];const header=rows[0].map(x=>x.trim());const idx=Object.fromEntries(HEADERS.map(h=>[h,header.indexOf(h)]));return rows.slice(1).map(repairRow).map(r=>Object.fromEntries(HEADERS.map(h=>[h,idx[h]>=0?(r[idx[h]]||'').trim():'']))).filter(x=>x.Company&&String(x['Active?']).toUpperCase()!=='FALSE').map(x=>({priority:x.Priority,company:x.Company,score:Number(x.Score)||0,status:x.Status,industry:x.Wedge,ownership:x['Owner / Backer'],employees:x.Employees,revenue:x.Revenue,growth:x['12m Growth'],bench:x['Tech / Data Bench'],complexity:x.Complexity,trigger:x.Trigger,exposure:x.Complexity,tension:x['Why Elastic'],hypothesis:x['Why Elastic'],whyElastic:x['Why Elastic'],unknown:x['Key Unknown'],question:x['Best Discovery Question'],buyer:x['Primary Buyer'],buyerName:x['Buyer Name'],contact:[x['Buyer Name'],x['Primary Buyer']].filter(Boolean).join(' · '),contactDetail:x['LinkedIn / Contact'],lastTouch:x['Last Touch'],nextAction:x['Next Action'],nextActionDate:x['Next Action Date'],outsideIn:x['Outside-In'],source:x['Source / Confidence'],notes:x.Notes,lastResearched:x['Last Researched'],active:x['Active?']})).sort((a,b)=>b.score-a.score);}
